_name: "Make indexes Config (default)"

input_path: "/content/drive/MyDrive/Hindi Audio/Kishore/features/mel"
output_path: "/content/drive/MyDrive/Hindi Audio/Kishore/features"

indexer_name: kishore

split_all:
  train: 80
  dev: 29

split_train:
  train: 200
  dev: 20
