_name: "Make indexes Config (default)"

input_path: "/Users/sameer/Downloads/cv-corpus-8.0-2022-01-19/hi/features/mel"
output_path: "/Users/sameer/Downloads/cv-corpus-8.0-2022-01-19/hi/features"

indexer_name: hindi

split_all:
  train: 200
  dev: 29

split_train:
  train: 200
  dev: 20
