_name: "Make indexes Config (default)"

input_path: "/content/drive/MyDrive/Hindi Audio/common_voice/features/mel"
output_path: "/content/drive/MyDrive/Hindi Audio/common_voice/features"

indexer_name: hindi

split_all:
  train: 200
  dev: 29

split_train:
  train: 200
  dev: 20
